name: Build Android APK (Capacitor)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Java (required for Gradle)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Android SDK tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y unzip wget lib32stdc++6 lib32z1
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline.zip
          mkdir -p $HOME/android-sdk/cmdline-tools
          unzip cmdline.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/tools
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          yes | $HOME/android-sdk/cmdline-tools/tools/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Install project dependencies
        run: |
          npm ci || npm install

      - name: Initialize Capacitor Android (if missing) and build
        run: |
          npx cap init "vscode-mobile-app" "com.example.vscodemobile" --web-dir=www --npm-client=npm || true
          npx cap add android || true
          npx cap copy android
          cd android
          ./gradlew assembleDebug -x lint

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: android/app/build/outputs/apk/debug/*.apk
